name: Snake Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  snake-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run Snake unit tests
        run: python -m unittest games/snake/tests/test_game_logic.py -v
